modLoader="javafml"
loaderVersion="[44,)"
license="All rights reserved"
issueTrackerURL="https://github.com/ricksouth/serilum-mc-mods/labels/Mod:%20Your%20Items%20Are%20Safe"
logoFile="icon.png"

[[mods]]
modId="youritemsaresafe"
version="3.2"
displayName="Your Items Are Safe"
displayURL="https://curseforge.com/minecraft/mc-mods/your-items-are-safe"
authors="Rick South"
description='''Generates a chest and armor stand at a player's death location to keep items from despawning. Highly configurable.
If you would like to contribute too, check out https://ricksouth.com/donate. Appreciate it! <3   
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  

Adam E, Alister, aternosorg, Cherriesaurus, Kreezxil, Michael W. S., Mir3JonCZ, nbtc971, Rebecca Hb., Robert Gilbert, Shana Gitnick, Sija, silver Bowsman, Tyler Behl   

If you would like to contribute too, check out https://ricksouth.com/donate. Appreciate it! <3   
'''

[[dependencies.youritemsaresafe]]
    modId="collective"
    mandatory=true
    versionRange="[6.53,)"
    ordering="NONE"
    side="BOTH"