modLoader="javafml"
loaderVersion="*"
license="All rights reserved"
issueTrackerURL="https://github.com/Serilum/.issue-tracker/labels/Mod:%20Your%20Items%20Are%20Safe"
logoFile="icon.png"

[[mods]]
modId="youritemsaresafe"
version="4.3"
displayName="Your Items Are Safe"
displayURL="https://serilum.com/mod/your-items-are-safe"
authors="Rick South"
description='''Generates a chest and armor stand at a player's death location to keep items from despawning. Highly configurable.
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  

Alister, Andrean Olgo, BirdieMiner, Cherriesaurus, Jack, Jeremy Langford, Michael W. S., Shana Gitnick, Tyler Behl   

If you would like to contribute too, check out https://serilum.com/donate. Appreciate it! <3   
'''

[[dependencies.youritemsaresafe]]
    modId="collective"
    type="required"
    mandatory=true
    versionRange="[7.41,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.youritemsaresafe]]
    modId="minecraft"
    type="required"
    mandatory=true
    versionRange="[1.20.4]"
    ordering="NONE"
    side="BOTH"

[[mixins]]
    config = "youritemsaresafe.mixins.json"